[build]
target = "thumbv7em-none-eabihf"

[unstable]
build-std = ["core", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[target.thumbv7em-none-eabihf]
rustflags = [
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=-mfloat-abi=softfp",
  "-C",
  "link-arg=-mcpu=cortex-m4",
]
